image: mcr.microsoft.com/dotnet/sdk:6.0-windowsservercore-ltsc2019

stages:
  - build
  - test

before_script:
  - dotnet --version

build:
  stage: build
  tags: [windows]
  script:
    - dotnet build Bomberman/Bomberman.sln

test:
  stage: test
  tags: [windows]
  script:
    - dotnet test Bomberman/Bomberman_Test/Bomberman_Test.csproj
